[features]
seeds = false
skip-lint = false

[programs.localnet]
legends_airdrop = "JD1UNr7Nmmg2wGYjJXcACWgPwQHJsqoE2YYWrEbjKmUm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sven/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
